baseURL = 'https://jesseprendergast.girhub.io'
languageCode = 'en-nz'
title = 'Jesse Prendergast'
theme = 'ananke'
pluralizeListTitles = false
[menu]
  [[menu.main]]
    identifier = "blog"
    name = "Blog"
    url = "/blog"
    weight = 1
   [[menu.main]]
   identifier = "about"
   name = "About"
   url = "/about"
   weight = 2
   [[menu.main]]
   identifier = "contact"
   name = "Contact"
   url = "/contact"
   weight = 3
   [[menu.main]]
   identifier = "portfolio"
   name = "Portfolio"
   url = "/portfolio/"
   weight = 4